#!/usr/bin/env bash
# Install nginx
# Run nginx on port 80 (default)
# Return Hello World at root /


sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
