#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

#sudo apt-get -y upgrade
#sudo apt-get -y update

#sudo apt-get -y install software-properties-common
#sudo add-apt repository -y ppa:vbernat/haproxy-2.0
#sudo apt-get -y update
#sudo apt-get -y install haproxy
sudo apt update
sudo apt-get -y install haproxy=1.6.\*
ha_cfg="/etc/haproxy/haproxy.cfg"
# ha_cfg="/home/victorvc/alx/alx-system_engineering-devops/0x0F-load_balancer/test"
st="\\\t"
nx="\n\t"
end="\n"
#def1="timeout http-request 10s$nx"
#def3="option httpclose$nx"
#defx="option forwardfor$end"

front="frontend haproxy$nx"
front1="bind *:80$nx"
front3="mode http$nx"
front2="default_backend my_servers$end"

back="backend my_servers$nx"
back1="balance roundrobin$nx"
back2="server 343517-web-02 3.89.160.146:80 check$nx"
back3="server 343517-web-01 34.229.70.213:80 check$end"

# sudo sed -i "\$a ENABLED=1" "/etc/default/haproxy"

# sudo sed -i "\$a $st${def1}${def3}${defx}${front}${front1}${front3}${front2}${back}${back1}${back2}${back3}" "$ha_cfg"

sudo sed -i "\$a $st${front}${front1}${front3}${front2}${back}${back1}${back2}${back3}" "$ha_cfg"
sudo service haproxy restart
