#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.

trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit 0" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT

echo "$$" > /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
