#!/usr/bin/env bash
# a Bash script that listens on port 98 on localhost.
# Terminal 1

# Connecting to localhost on port 98 using telnet and typing some text.

# sylvain@ubuntu$ telnet localhost 98
# Trying 127.0.0.2...
# Connected to localhost.
# Escape character is '^]'.
# Hello world
# test

# Terminal 0
# Receiving the text on the other side.

# $ sudo ./100-port_listening_on_localhost
# Hello world
# test

nc -l 98
