#!/usr/bin/env bash
# debugging 2: run nginx on port 8080 as user: nginx
# security protocol: access control
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
chown -R nginx /etc/nginx /var/log/nginx /usr/share/nginx /run/nginx.pid
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx nginx
