#!/usr/bin/env bash
# short and sweet version of 1-run_nginx_as_nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
chown -R nginx /etc/nginx /var/log/nginx /usr/share/nginx /run/nginx.pid
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx nginx
