#!/usr/bin/env bash
# Soft restarts gunicorn

ps faux | grep gunicorn | grep web_flask.0-hello_route | awk '{ print $2 }' | xargs kill -HUP
# sudo kill -HUP "$(ps -C gunicorn fch -o pid | head -n 1)"
#kill -s SIGHUP "$gpid"
